### ISSUE TITLE
Directly importing .ics into macOS calendar returns 0:00~24:00 events instead of full day

### ISSUE THREAD

**Issue by austinhuang0131** [zagushka/birthday-calendar-extractor#10]
Importing into Google Calendar then exporting it from Google Calendar seems to be a workaround.

**Comment by zagushka** [comment]
@austinhuang0131 thank you for the bug report. Fixed and waiting for review.

**Comment by austinhuang0131** [comment]
Just redownloaded it. Nope.

![Screen Shot 2021-01-23 at 14 28 02](https://user-images.githubusercontent.com/16656689/105612074-64521080-5d87-11eb-8ae8-6bd6ce4b6596.png)

**Comment by zagushka** [comment]
> Just redownloaded it. Nope.
> 
> ![Screen Shot 2021-01-23 at 14 28 02](https://user-images.githubusercontent.com/16656689/105612074-64521080-5d87-11eb-8ae8-6bd6ce4b6596.png)
> 
> Mojave macOS calendar

Yes, you are right. Merged wrong branch.

**Comment by zagushka** [comment]
@austinhuang0131 should be fine now. Thanks.
