### ISSUE TITLE
Cannot import due to false incorrect language

### ISSUE THREAD

**Issue by mcc-osmo** [zagushka/birthday-calendar-extractor#16]
When I try to use this, it says that my language must be English(US), English(UK), etc.. I have changed my language back and forth between those two and it continue to complain that my language is incorrect.

**Comment by milos9680** [comment]
I have the same problem

**Comment by zagushka** [comment]
Thanks for report.

Fixed  086b52cf0c075725d9fa6b709848623cd41a8d97 
Already deployed v3.0.1
