### ISSUE TITLE
Script failed to scan birthdays

### ISSUE THREAD

**Issue by amreggie** [zagushka/birthday-calendar-extractor#17]
Script failed to scan birthdays.
Error message: eyJ0eXBlIjoiU0NBTl9FUlJPUl9USU1FT1VUIn0=

"It take too long to fulfill extraction process. Please try again.
Also you can use the text below to open a bug, I'll do my best to fix it as soon as possible."

**Comment by mitchpaquette** [comment]
I am having the same issue

**Comment by zagushka** [comment]
@amreggie @mitchpaquette 
I have released adc8619cbbce29005ca6300c49fa90b94ec8352f on version 3.0.3
Can you please confirm it fixes your issue.
