### ISSUE TITLE
Facebook (new interface) doesn't show December birthdays regardless of language

### ISSUE THREAD

**Issue by austinhuang0131** [zagushka/birthday-calendar-extractor#26]
Even if I switch to one of the 4 supported language, https://www.facebook.com/friends/birthdays still does not show December birthdays (I do have friends born in December), and your extension also fails to get them. Obviously it's an upstream issue, but just letting you know.

**Comment by austinhuang0131** [comment]
Update: December birthdays do show on https://m.facebook.com/events/calendar/birthdays

**Comment by zagushka** [comment]
Adding custom birthdates added in #94
