### ISSUE TITLE
Language error in spite being English UK or US.

### ISSUE THREAD

**Issue by Scelvin** [zagushka/birthday-calendar-extractor#28]
Error: SCAN_LOG_CHECK_LOGIN_ERROR_LANGUAGE

**Comment by kenstar-36** [comment]
I encountered it too. I wish I can help but I know nothing about coding, could I also be enlightened as to why this happens?
I tried changing English UK > US> UK > US but still to no avail.

Error message:
Script was able to scan all the months, but December.
Old Facebook api is used to scan December, please change Facebook language to English (UK), English (US), Русский, Українська or עברית, and scan again.

**Comment by kenstar-36** [comment]
Hmm, I just checked again and Facebook itself is missing December...
![image](https://user-images.githubusercontent.com/85157204/120770093-5d66b600-c550-11eb-9a76-03406c0ead43.png)

**Comment by emorcelle** [comment]
Hello!,
I have the same problem. But in my execution of the APP in December 2021, the data of the birthdays of November 2022 disappears..
![Capture](https://user-images.githubusercontent.com/95543791/144720475-4794a6f7-2b46-4d30-8295-53c25cd0a845.PNG)

**Comment by TomerVagenfeld** [comment]
Please note that the error message: SCAN_LOG_CHECK_LOGIN_ERROR_LANGUAGE is alerting but the actual December data is extracted correctly. 
I did change languages and the final output contains December. 
 
![image](https://user-images.githubusercontent.com/22561598/151173921-fb24c694-3482-4be6-aec2-bf90e95fb7bd.png)

**Comment by zagushka** [comment]
Scanning issue was fixed in https://github.com/zagushka/birthday-calendar-extractor/pull/94
