### ISSUE TITLE
Error Encountered When Running Extractor

### ISSUE THREAD

**Issue by funkeyfreak** [zagushka/birthday-calendar-extractor#30]
Script failed to scan birthdays.
Error message: eyJlcnJvciI6IlJlbW92ZWQgaW5maW5pdGUgc2NhbiBsb2NrIiwidHlwZSI6IlNDQU5fRVJST1JfR0VORVJBTCJ9

**Comment by zagushka** [comment]
Scanning issue was fixed in https://github.com/zagushka/birthday-calendar-extractor/pull/94
