### ISSUE TITLE
Unable to generate calendar

### ISSUE THREAD

**Issue by StarkPrince** [zagushka/birthday-calendar-extractor#33]
Script failed to scan birthdays.
Error message: eyJ0eXBlIjoiU0NBTl9FUlJPUl9USU1FT1VUIn0=

**Comment by simllll** [comment]
Same for me, can't really tell what this error message is about

**Comment by zagushka** [comment]
Scanning issue was fixed in https://github.com/zagushka/birthday-calendar-extractor/pull/94
