### ISSUE TITLE
Script failed to scan birthdays. Error message: eyJ0eXBlIjoiU0NBTl9FUlJPUl9USU1FT1VUIn0=

### ISSUE THREAD

**Issue by JavoJavo** [zagushka/birthday-calendar-extractor#37]
It take too long to fulfill extraction process. Please try again.

**Comment by vehanlandman** [comment]
Just got the same error message. 
Script failed to scan birthdays.
Error message: eyJ0eXBlIjoiU0NBTl9FUlJPUl9USU1FT1VUIn0=

**Comment by zagushka** [comment]
Adding custom birthdates added in https://github.com/zagushka/birthday-calendar-extractor/pull/94
