### ISSUE TITLE
Script failed to scan birthdays

### ISSUE THREAD

**Issue by Squirl1899** [zagushka/birthday-calendar-extractor#38]
Script failed to scan birthdays.
Error message: eyJlcnJvciI6IlJlb
W92ZWQgaW5maW5pdGUgc2NhbiBsb2NrIiwidHlwZSI6IlNDQU5fRVJST1JfR0VORVJBTCJ9

I changed the language to UK and scanned again and same error.

I then changed the language to US and scanned again and same error.

![image](https://user-images.githubusercontent.com/37461404/197834046-fe85757c-6391-4f69-804c-71a6a05c6e0d.png)

**Comment by zagushka** [comment]
Adding custom birthdates added in https://github.com/zagushka/birthday-calendar-extractor/pull/94
