### ISSUE TITLE
Give possibility to select CSV columns

### ISSUE THREAD

**Issue by eximius313** [zagushka/birthday-calendar-extractor#45]
There is a great Birthday Reminder app (https://birthday-calendar.app/) but it expects data to be in the format of:
`Name,Date` where `Date` could be either `yyyy-MM-dd` or `MM-dd` (when the year is null), while on the other hand - your Plugin exports CSV in the format of: 
`"Name","Year","Month","Day","Link to Profile"` (where the missing year is explicitly represened as string "null").

It would be great if you allow to select which coulumns to output in the CSV

**Comment by zagushka** [comment]
You can always update the downloaded CSV the way you like.
