### ISSUE TITLE
Script failed to scan birthdays.

### ISSUE THREAD

**Issue by eximius313** [zagushka/birthday-calendar-extractor#46]
Error message: eyJlcnJvciI6IlJlbW92ZWQgaW5maW5pdGUgc2NhbiBsb2NrIiwidHlwZSI6IlNDQU5fRVJST1JfR0VORVJBTCJ9

It happened right after it showed the error dialog, that it was unable to scan December and suggested to change language to english. 
I closed that dialog, headed to "Calendar Generator" and then this error appeared.

**Comment by zagushka** [comment]
The issue is solved in https://github.com/zagushka/birthday-calendar-extractor/pull/94
