### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Developer122436** [zagushka/birthday-calendar-extractor#58]
Script failed to scan birthdays.
Error message: eyJ0eXBlIjoiU0NBTl9FUlJPUl9USU1FT1VUIn0=

**Comment by Developer122436** [comment]
Script failed to scan birthdays.
Error message: eyJ0eXBlIjoiU0NBTl9FUlJPUl9USU1FT1VUIn0=

**Comment by zagushka** [comment]
The issue is solved in https://github.com/zagushka/birthday-calendar-extractor/pull/94
