### ISSUE TITLE
Script failed to scan birthdays. [Solution - Leave Open]

### ISSUE THREAD

**Issue by GrandadsJumper** [zagushka/birthday-calendar-extractor#66]
Hey you're likely having the same issue as I had ...

- you login to facebook 
- Press scan
- And you're hit with the following error
![image](https://github.com/zagushka/birthday-calendar-extractor/assets/35103244/4ff0ef20-0e0c-4dc6-85cb-93b145752237)

Here are a few steps I took to get this tool working.

1. Disable any ad blocking extensions you have active 
2. Head to https://www.facebook.com/settings/?tab=language and make sure your _language_ is English (UK) and the _Formats for dates, times and numbers_ is UK (English). [Note: other settings may work, I just know this combo worked for me.]
![image](https://github.com/zagushka/birthday-calendar-extractor/assets/35103244/d60ae3f6-2dcf-4bd5-ab87-5c99e2ba2286)
3. Finally, you can run the scan - do expect the following error but do not worry the error message is not correct, you do infact have all your friends birthdays exported.
![image](https://github.com/zagushka/birthday-calendar-extractor/assets/35103244/76067308-8d88-4722-bb59-0b321d8fdd25)

Now, press the "Calander generator" button at the bottom of the extension, then GENERATE AND DOWNLOAD to get a copy of all your friends birthdays in an .ics file. 

👍🎂 BIG THANK YOU TO THE DEVELOPER FOR THE WORK THEY PUT INTO MAKING THIS EXTENSION ! 👍🎂

**Comment by Camilafreddo** [comment]
didnt work

**Comment by Allenfm** [comment]
Didn't work for me either

**Comment by dinizm** [comment]
Tried, but it didn't work

**Comment by zagushka** [comment]
Hey, @GrandadsJumper 
I really appreciate your solution, and thank you for sharing it with everyone.

I'm back after a huge break from this extension and released the new version that is supposed to deal with this issue: https://github.com/zagushka/birthday-calendar-extractor/pull/94

Thanks again 🙏
