### ISSUE TITLE
birthday calander exporter issue

### ISSUE THREAD

**Issue by sandeepjangid44** [zagushka/birthday-calendar-extractor#67]
![Capture1](https://github.com/zagushka/birthday-calendar-extractor/assets/143335233/9ac54f74-1342-4079-b760-f409f297945e
![Capture1](https://github.com/zagushka/birthday-calendar-extractor/assets/143335233/3c070154-704a-419f-ae11-ccd00e3e8ed8)

Hi, I tried to generate the calander using the extension. but showing bugs attached in the screenshot. Please help for the needful.

**Comment by zagushka** [comment]
Scanning issue was fixed in https://github.com/zagushka/birthday-calendar-extractor/pull/94
